### ISSUE TITLE
Change Redis driver to use incrby methods

### ISSUE THREAD

**Issue by goophps** [MasoniteFramework/masonite#680] opened 2022-06-24 08:58 UTC
### Describe the bug

Hi, why do you want to do this? and poor performance
![image](https://user-images.githubusercontent.com/49714224/175500728-9b8d5b1b-c7e3-4709-94a3-706dbef10efe.png)

Why not do this?
![image](https://user-images.githubusercontent.com/49714224/175501117-59da5554-0d40-4697-b377-de4ffcd6659a.png)

### OS

Linux

### OS version

deepin

### Masonite Version

4.15.0

**Comment by goophps** [comment] 2022-06-25 07:11
Hello, don't write this code like this, it provides the correct way to write it, why not use it?

**Comment by josephmancuso** [comment] 2022-06-25 10:40
We will get to it. The issue is open I didn't close it. If you want to see this fixed then please open a PR and I will review it. If not then please wait until we get to this issue

**Comment by goophps** [comment] 2022-06-25 19:43
thank you for your work

**Comment by circulon** [comment] 2022-06-26 04:11
@josephmancuso  
Using Driver native methods where they exist would be preferable as it incurs less overhead (hits on the store).

**Comment by circulon** [comment] 2022-06-27 08:05
@josephmancuso 
This is really a moot point now as PR #686 covers this by updating an internal cache for these methods
eg `.increment()` and `.decrement()` so the native driver methods are no longer relevant to setting incremented/decremented values directly in the store

**Closed as completed** 2022-10-09 12:50 UTC
Labels: enhancement
